# Site settings
title: PeTu Blog
SEOTitle: 彭拓的博客 | PeTu Blog
header-img: img/home-bg.jpg
email: peng_tuo@foxmail.com
description: "天下事有难易乎？为之，则难者亦易矣；不为，则易者亦难矣。"
keyword: ""
url: "http://www.pengtuo.tech"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
weibo_username:     Pe-Tu
zhihu_username:     peng-tuo-45
github_username:    pteric
jianshu_username:   PeTu



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter:    rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: a4e954214ceaf16ab427efba6135201f
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: pengtuo.tech



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "你最可爱，我说时来不及思索，但思索之后，还是这样说。"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Tony Bai(Golang)",
        href: "https://tonybai.com/articles/"
    },
    {
        title: "Hux",
        href: "http://huangxuan.me"
    },
    {
        title: "asdfv1929",
        href: "https://asdfv1929.github.io"
    },
    {
        title: "Moshi",
        href: "https://liujunzhou.cn"
    }
]

comments: true

gitalk:
    enable: true #是否开启
    githubID: pteric #你的Github用户名
    repo: pteric.github.io #Github仓库名称
    ClientID: d9b1d23f344173cc2656 #创建的Application ClientID
    ClientSecret: 34ddd5b4744d72ef6c59bac27c9c1c25c65f5546 #创建的Application ClientSecret
    adminUser: pteric # 评论初始化账户(GitHub ID)
    distractionFreeMode: true # 是否开启分心自由模式 也就是免打扰
